// This file is generated by the server. Do not edit it manually.

// Declare enums
declare enum MoveDirectionType {
  North = 0,
  South = 1,
  East = 2,
  West = 3,
  NorthEast = 4,
  NorthWest = 5,
  SouthEast = 6,
  SouthWest = 7,
}


declare enum ItemRarityType {
  Common = 0,
  Uncommon = 1,
  Rare = 2,
  Epic = 3,
  Legendary = 4,
}


declare enum MapType {
  World = 0,
  Dungeon = 1,
  City = 2,
  Town = 3,
  Village = 4,
  Camp = 5,
  Ruins = 6,
  Cave = 7,
  Forest = 8,
}


declare enum WorldMessageType {
  Whisper = 5,
  Normal = 10,
  Yell = 15,
}


declare enum EquipLocationType {
  None = 0,
  Head = 1,
  Neck = 2,
  Shoulders = 4,
  Chest = 8,
  Back = 16,
  Wrists = 32,
  Hands = 64,
  Waist = 128,
  Legs = 256,
  Feet = 512,
  Ring = 1024,
  Trinket = 2048,
  MainHand = 4096,
  OffHand = 8192,
  Ranged = 16384,
  Ammo = 32768,
}


declare enum MapGeneratorType {
  RectangleMap = 0,
  CellularAutomata = 1,
  Dungeon = 2,
  BasicRandomRooms = 3,
}


declare interface AiContext {
  NpcGameObject: any;
  NpcEntity: any;
  MapId: string;
  Logger: any;
  PlayerService: any;
  WorldService: any;
  EventBus: any;
  Data: any;
}



declare interface AiContext {
  NpcGameObject: any;
  NpcEntity: any;
  MapId: string;
  Logger: any;
  PlayerService: any;
  WorldService: any;
  EventBus: any;
  Data: any;
}



declare interface BlueprintGenerationMapContext {
  GameObjects: any;
  Npcs: any;
}


declare interface BlueprintGenerationMapContext {
  GameObjects: any;
  Npcs: any;
}



declare interface BlueprintGenerationMapContext {
  GameObjects: any;
  Npcs: any;
}


declare interface BlueprintGenerationMapContext {
  GameObjects: any;
  Npcs: any;
}



declare interface BlueprintGenerationMapContext {
  GameObjects: any;
  Npcs: any;
}


declare interface BlueprintGenerationMapContext {
  GameObjects: any;
  Npcs: any;
}



declare interface BlueprintMapInfoContext {
  MapType: MapType;
  Width: number;
  Height: number;
  MapStrategy: number;
  BlockingTile: any;
  NonBlockingTile: any;
}


declare interface BlueprintMapInfoContext {
  MapType: MapType;
  Width: number;
  Height: number;
  MapStrategy: number;
  BlockingTile: any;
  NonBlockingTile: any;
}



declare interface Action {
  Target: any;
  Method: any;
}


declare interface GameObjectContext {
  MapId: string;
  GameObject: any;
  SenderId: any;
  IsNpc: boolean;
}



declare interface GameObjectContext {
  MapId: string;
  GameObject: any;
  SenderId: any;
  IsNpc: boolean;
}
// Declare constants
declare const TILE_DEFAULT_DEFAULT_NULL: number;
declare const TILE_DEFAULT_DEFAULT_WHITE: number;
declare const TILE_DEFAULT_DEFAULT_BLACK: number;
declare const TILE_TERRAIN_WATER_WATER_1: number;
declare const TILE_TERRAIN_WATER_WATER_2: number;
declare const TILE_TERRAIN_WATER_WATER_3: number;
declare const TILE_TERRAIN_WATER_WATER_4: number;
declare const TILE_TERRAIN_WATER_WATER_5: number;
declare const TILE_TERRAIN_GRASS_GRASS_1: number;
declare const TILE_TERRAIN_GRASS_GRASS_2: number;
declare const TILE_TERRAIN_GRASS_GRASS_3: number;
declare const TILE_TERRAIN_GRASS_GRASS_4: number;
declare const TILE_TERRAIN_GRASS_GRASS_5: number;
declare const TILE_TERRAIN_GRASS_GRASS_6: number;
declare const TILE_TERRAIN_GRASS_GRASS_7: number;
declare const TILE_TERRAIN_GRASS_GRASS_8: number;
declare const TILE_TERRAIN_GRASS_GRASS_9: number;
declare const TILE_TERRAIN_GRASS_GRASS_10: number;
declare const TILE_TERRAIN_GRASS_GRASS_11: number;
declare const TILE_TERRAIN_GRASS_GRASS_12: number;
declare const TILE_TERRAIN_GRASS_ROCKS_1: number;
declare const TILE_TERRAIN_GRASS_ROCKS_2: number;
declare const TILE_TERRAIN_GRASS_ROCKS_3: number;
declare const TILE_TERRAIN_GRASS_ROCKS_4: number;
declare const TILE_TERRAIN_GRASS_ROCKS_5: number;
declare const TILE_TERRAIN_GRASS_ROCKS_6: number;
declare const TILE_TERRAIN_GRASS_ROCKS_7: number;
declare const TILE_TERRAIN_GRASS_ROCKS_8: number;
declare const TILE_TERRAIN_GRASS_ROCKS_9: number;
declare const TILE_TERRAIN_GRASS_ROCKS_10: number;
declare const TILE_TERRAIN_LAVA_LAVA_1: number;
declare const TILE_TERRAIN_LAVA_LAVA_2: number;
declare const TILE_WALL_STONE_STONE_1: number;
declare const TILE_WALL_STONE_STONE_2: number;
declare const TILE_WALL_STONE_STONE_3: number;
declare const TILE_WALL_STONE_STONE_4: number;
declare const TILE_WALL_STONE_STONE_5: number;
declare const TILE_WALL_STONE_STONE_6: number;
declare const TILE_WALL_STONE_STONE_7: number;
declare const TILE_TERRAIN_BUSH_BUSH_1: number;
declare const TILE_TERRAIN_BUSH_BUSH_2: number;
declare const TILE_TERRAIN_BUSH_BUSH_3: number;
declare const TILE_TERRAIN_BUSH_BUSH_4: number;
declare const TILE_TERRAIN_BUSH_BUSH_5: number;
declare const TILE_TERRAIN_BUSH_BUSH_6: number;
declare const TILE_TERRAIN_BUSH_BUSH_7: number;
declare const TILE_TERRAIN_BUSH_BUSH_8: number;
declare const TILE_TERRAIN_BUSH_BUSH_9: number;
declare const TILE_TERRAIN_BUSH_BUSH_10: number;
declare const TILE_TERRAIN_BUSH_BUSH_11: number;
declare const TILE_TERRAIN_BUSH_BUSH_12: number;
declare const TILE_TERRAIN_BUSH_BUSH_13: number;
declare const TILE_TERRAIN_BUSH_BUSH_14: number;
declare const TILE_TERRAIN_BUSH_BUSH_15: number;
declare const TILE_TERRAIN_BUSH_BUSH_16: number;
declare const TILE_TERRAIN_BUSH_BUSH_17: number;
declare const TILE_TERRAIN_BUSH_BUSH_18: number;
declare const TILE_TERRAIN_BUSH_BUSH_19: number;
declare const TILE_TERRAIN_BUSH_BUSH_20: number;
declare const TILE_TERRAIN_BUSH_BUSH_21: number;
declare const TILE_TERRAIN_BUSH_BUSH_22: number;
declare const TILE_TERRAIN_BUSH_BUSH_23: number;
declare const TILE_TERRAIN_BUSH_BUSH_24: number;
declare const TILE_TERRAIN_BUSH_BUSH_25: number;
declare const TILE_TERRAIN_BUSH_BUSH_26: number;
declare const TILE_TERRAIN_BUSH_BUSH_27: number;
declare const TILE_TERRAIN_BUSH_BUSH_28: number;
declare const TILE_TERRAIN_BUSH_BUSH_29: number;
declare const TILE_TERRAIN_BUSH_BUSH_30: number;
declare const TILE_TERRAIN_BUSH_BUSH_31: number;
declare const TILE_TERRAIN_BUSH_BUSH_32: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_1: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_2: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_3: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_4: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_5: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_6: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_7: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_8: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_9: number;
declare const TILE_TERRAIN_BUSH_FLOWERS_10: number;
declare const TILE_TERRAIN_TREE_TREE_1: number;
declare const TILE_TERRAIN_TREE_TREE_2: number;
declare const TILE_TERRAIN_TREE_TREE_3: number;
declare const TILE_TERRAIN_TREE_TREE_4: number;
declare const TILE_TERRAIN_TREE_TREE_5: number;
declare const TILE_TERRAIN_TREE_TREE_6: number;
declare const TILE_TERRAIN_TREE_TREE_7: number;
declare const TILE_TERRAIN_TREE_TREE_8: number;
declare const TILE_TERRAIN_TREE_TREE_9: number;
declare const TILE_TERRAIN_TREE_TREE_10: number;
declare const TILE_TERRAIN_TREE_TREE_11: number;
declare const TILE_TERRAIN_TREE_TREE_12: number;
declare const TILE_TERRAIN_TREE_TREE_13: number;
declare const TILE_TERRAIN_TREE_TREE_14: number;
declare const TILE_TERRAIN_TREE_TREE_15: number;
declare const TILE_TERRAIN_TREE_TREE_16: number;
declare const TILE_TERRAIN_TREE_TREE_17: number;
declare const TILE_TERRAIN_TREE_TREE_18: number;
declare const TILE_TERRAIN_TREE_TREE_19: number;
declare const TILE_TERRAIN_TREE_TREE_20: number;
declare const TILE_TERRAIN_TREE_TREE_21: number;
declare const TILE_TERRAIN_TREE_TREE_22: number;
declare const TILE_TERRAIN_TREE_TREE_23: number;
declare const TILE_TERRAIN_TREE_TREE_24: number;
declare const TILE_TERRAIN_TREE_TREE_25: number;
declare const TILE_TERRAIN_TREE_TREE_26: number;
declare const TILE_TERRAIN_TREE_TREE_27: number;
declare const TILE_TERRAIN_TREE_TREE_28: number;
declare const TILE_TERRAIN_TREE_TREE_29: number;
declare const TILE_TERRAIN_TREE_TREE_30: number;
declare const TILE_TERRAIN_TREE_TREE_31: number;
declare const TILE_TERRAIN_TREE_TREE_32: number;
declare const TILE_TERRAIN_TREE_TREE_33: number;
declare const TILE_TERRAIN_TREE_TREE_34: number;
declare const TILE_TERRAIN_TREE_TREE_35: number;
declare const TILE_TERRAIN_TREE_TREE_36: number;
declare const TILE_TERRAIN_TREE_TREE_37: number;
declare const TILE_TERRAIN_TREE_TREE_38: number;
declare const TILE_TERRAIN_TREE_TREE_39: number;
declare const TILE_TERRAIN_TREE_TREE_40: number;
declare const TILE_TERRAIN_TREE_TREE_41: number;
declare const TILE_TERRAIN_TREE_TREE_42: number;
declare const TILE_TERRAIN_TREE_TREE_43: number;
declare const TILE_TERRAIN_TREE_TREE_44: number;
declare const TILE_TERRAIN_TREE_TREE_45: number;
declare const TILE_TERRAIN_TREE_TREE_46: number;
declare const TILE_TERRAIN_TREE_TREE_47: number;
declare const TILE_TERRAIN_TREE_TREE_48: number;
declare const TILE_TERRAIN_TREE_TREE_49: number;
declare const TILE_TERRAIN_TREE_TREE_50: number;
declare const TILE_TERRAIN_TREE_TREE_51: number;
declare const TILE_TERRAIN_TREE_TREE_52: number;
declare const TILE_TERRAIN_TREE_TREE_53: number;
declare const TILE_TERRAIN_TREE_TREE_54: number;
declare const TILE_TERRAIN_TREE_TREE_55: number;
declare const TILE_TERRAIN_TREE_TREE_56: number;
declare const TILE_TERRAIN_TREE_TREE_57: number;
declare const TILE_TERRAIN_TREE_TREE_58: number;
declare const TILE_TERRAIN_TREE_TREE_59: number;
declare const TILE_TERRAIN_TREE_TREE_60: number;
declare const TILE_TERRAIN_TREE_TREE_61: number;
declare const TILE_TERRAIN_TREE_TREE_62: number;
declare const TILE_TERRAIN_TREE_TREE_63: number;
declare const TILE_TERRAIN_TREE_TREE_64: number;
declare const TILE_HOUSE_FLOOR_FLOOR_1: number;
declare const TILE_HOUSE_FLOOR_FLOOR_2: number;
declare const TILE_HOUSE_FLOOR_FLOOR_3: number;
declare const TILE_HOUSE_FLOOR_FLOOR_4: number;
declare const TILE_HOUSE_FLOOR_FLOOR_5: number;
declare const TILE_HOUSE_FLOOR_FLOOR_6: number;
declare const TILE_HOUSE_FLOOR_FLOOR_7: number;
declare const TILE_HOUSE_FLOOR_FLOOR_8: number;
declare const TILE_HOUSE_FLOOR_FLOOR_9: number;
declare const TILE_HOUSE_FLOOR_FLOOR_10: number;
declare const TILE_HOUSE_FLOOR_FLOOR_11: number;
declare const TILE_HOUSE_FLOOR_FLOOR_12: number;
declare const TILE_HOUSE_FLOOR_FLOOR_13: number;
declare const TILE_HOUSE_FLOOR_FLOOR_14: number;
declare const TILE_HOUSE_FLOOR_FLOOR_15: number;
declare const TILE_HOUSE_FLOOR_FLOOR_16: number;
declare const TILE_HOUSE_FLOOR_FLOOR_17: number;
declare const TILE_HOUSE_FLOOR_FLOOR_18: number;
declare const TILE_HOUSE_FLOOR_FLOOR_19: number;
declare const TILE_HOUSE_FLOOR_FLOOR_20: number;
declare const TILE_HOUSE_FLOOR_FLOOR_21: number;
declare const TILE_HOUSE_FLOOR_FLOOR_22: number;
declare const TILE_HOUSE_FLOOR_FLOOR_23: number;
declare const TILE_HOUSE_FLOOR_FLOOR_24: number;
declare const TILE_HOUSE_FLOOR_FLOOR_25: number;
declare const TILE_HOUSE_FLOOR_FLOOR_26: number;
declare const TILE_HOUSE_FLOOR_FLOOR_27: number;
declare const TILE_HOUSE_FLOOR_FLOOR_28: number;
declare const TILE_HOUSE_FLOOR_FLOOR_29: number;
declare const TILE_HOUSE_FLOOR_FLOOR_30: number;
declare const TILE_HOUSE_FLOOR_FLOOR_31: number;
declare const TILE_HOUSE_FLOOR_FLOOR_32: number;
declare const TILE_HOUSE_WOOD_WALL_1: number;
declare const TILE_HOUSE_WOOD_COLUMN_1: number;
declare const TILE_HOUSE_WOOD_WINDOW_1: number;
declare const TILE_HOUSE_WOOD_WINDOW_2: number;
declare const TILE_HOUSE_WOOD_WINDOW_3: number;
declare const TILE_HOUSE_WOOD_DOOR_1: number;
declare const TILE_HOUSE_WOOD_DOOR_2: number;
declare const TILE_HOUSE_WOOD_DECORATION_1: number;
declare const TILE_HOUSE_WOOD_DECORATION_2: number;
declare const TILE_TERRAIN_PROPS_CAMPFIRE_1: number;
declare const TILE_HOUSE_WOOD_WINDOW_4: number;
declare const TILE_HOUSE_WOOD_WINDOW_5: number;
declare const TILE_HOUSE_WOOD_WINDOW_6: number;
declare const TILE_HOUSE_WOOD_WINDOW_7: number;
declare const TILE_HOUSE_WOOD_WINDOW_8: number;
declare const TILE_HOUSE_WOOD_WINDOW_9: number;
declare const TILE_HOUSE_WOOD_WINDOW_10: number;
declare const TILE_HOUSE_WOOD_WINDOW_11: number;
declare const TILE_HOUSE_WOOD_WINDOW_12: number;
declare const TILE_HOUSE_WOOD_WINDOW_13: number;
declare const TILE_HOUSE_WOOD_WINDOW_14: number;
declare const TILE_HOUSE_WOOD_WINDOW_15: number;
declare const TILE_HOUSE_WOOD_WINDOW_16: number;
declare const TILE_HOUSE_WOOD_WINDOW_17: number;
declare const TILE_HOUSE_WOOD_WINDOW_18: number;
declare const TILE_HOUSE_WOOD_WINDOW_19: number;
declare const TILE_HOUSE_WOOD_WINDOW_20: number;
declare const TILE_HOUSE_WOOD_WINDOW_21: number;
declare const TILE_HOUSE_WOOD_WINDOW_22: number;
declare const TILE_HOUSE_WOOD_WINDOW_23: number;
declare const TILE_HOUSE_WOOD_WINDOW_24: number;
declare const TILE_HOUSE_WOOD_WINDOW_25: number;
declare const TILE_HOUSE_WOOD_WINDOW_26: number;
declare const TILE_HUMANS_CLASSES_MAGE_1: number;
declare const TILE_HUMANS_CLASSES_MAGE_2: number;
declare const TILE_HUMANS_CLASSES_MAGE_3: number;
declare const TILE_HUMANS_CLASSES_MAGE_4: number;
declare const TILE_HUMANS_CLASSES_MAGE_5: number;
declare const TILE_HUMANS_CLASSES_MAGE_6: number;
declare const TILE_HUMANS_CLASSES_MAGE_7: number;
declare const TILE_HUMANS_CLASSES_MAGE_8: number;
declare const TILE_HUMANS_CLASSES_MAGE_9: number;
declare const TILE_HUMANS_CLASSES_WARRIOR_1: number;
declare const TILE_HUMANS_CLASSES_WARRIOR_2: number;
declare const TILE_HUMANS_CLASSES_WARRIOR_3: number;
declare const TILE_HUMANS_CLASSES_WARRIOR_5: number;
declare const TILE_HUMANS_CLASSES_PRIEST_1: number;
declare const TILE_HUMANS_CLASSES_PRIEST_2: number;
declare const TILE_HUMANS_CLASSES_PRIEST_4: number;
declare const TILE_HUMANS_CLASSES_ROGUE_1: number;
declare const TILE_HUMANS_CLASSES_ROGUE_2: number;
declare const TILE_HUMANS_CLASSES_ROGUE_3: number;
declare const TILE_HUMANS_CLASSES_ROGUE_4: number;
declare const TILE_HUMANS_CLASSES_ROGUE_5: number;
declare const TILE_HUMANS_CLASSES_ROGUE_6: number;
declare const TILE_ELF_CLASSES_ROGUE_1: number;
declare const TILE_ELF_CLASSES_ROGUE_2: number;
declare const TILE_ELF_CLASSES_ROGUE_3: number;
declare const TILE_ELF_CLASSES_ROGUE_4: number;
declare const TILE_ELF_CLASSES_ROGUE_5: number;
declare const TILE_ELF_CLASSES_ROGUE_6: number;
declare const TILE_HUMANS_HUMANS_KID_1: number;
declare const TILE_HUMANS_HUMANS_FARMER_1: number;
declare const TILE_HUMANS_HUMANS_FARMER_2: number;
declare const TILE_HUMANS_HUMANS_FARMER_3: number;
declare const TILE_HUMANS_HUMANS_FARMER_4: number;
declare const TILE_HUMANS_HUMANS_FARMER_5: number;
declare const TILE_HUMANS_HUMANS_SCOUT_1: number;
declare const TILE_HUMANS_HUMANS_SCOUT_2: number;
declare const TILE_HUMANS_HUMANS_JESTER_1: number;
declare const TILE_MONSTERS_MONSTERS_RAT_1: number;
declare const TILE_MONSTERS_MONSTERS_RAT_2: number;
declare const TILE_MONSTERS_MONSTERS_RAT_3: number;
declare const TILE_MONSTERS_MONSTERS_RAT_4: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_1: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_2: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_3: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_4: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_5: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_6: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_7: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_8: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_9: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_10: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_11: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_12: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_13: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_14: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_15: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_16: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_17: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_18: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_19: number;
declare const TILE_MONSTERS_MONSTERS_SNAKE_20: number;
declare const TILE_MONSTERS_MONSTERS_TRIHEAD_1: number;
declare const TILE_MONSTERS_MONSTERS_TRIHEAD_2: number;
declare const TILE_MONSTERS_MONSTERS_TRIHEAD_3: number;
declare const TILE_MONSTERS_MONSTERS_TRIHEAD_4: number;
declare const TILE_MONSTERS_MONSTERS_TRIHEAD_5: number;
declare const TILE_MONSTERS_MONSTERS_TRIHEAD_6: number;
declare const TILE_MONSTERS_MONSTERS_TRIHEAD_7: number;
declare const TILE_MONSTERS_MONSTERS_TRIHEAD_8: number;
declare const TILE_MONSTERS_MONSTERS_TRIHEAD_9: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_1: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_2: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_3: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_4: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_5: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_6: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_7: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_8: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_9: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_10: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_11: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_12: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_13: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_14: number;
declare const TILE_MONSTERS_MONSTERS_MEDUSA_15: number;
declare const TILE_MONSTERS_MONSTERS_THING_1: number;
declare const TILE_MONSTERS_MONSTERS_THING_2: number;
declare const TILE_MONSTERS_MONSTERS_THING_3: number;
declare const TILE_MONSTERS_MONSTERS_THING_4: number;
declare const TILE_MONSTERS_MONSTERS_THING_5: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_1: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_2: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_3: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_4: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_5: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_6: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_7: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_8: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_9: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_10: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_11: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_12: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_13: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_14: number;
declare const TILE_MONSTERS_MONSTERS_GHOST_15: number;
declare const TILE_MONSTERS_MONSTERS_BUG_1: number;
declare const TILE_MONSTERS_MONSTERS_BUG_2: number;
declare const TILE_MONSTERS_MONSTERS_BUG_3: number;
declare const TILE_MONSTERS_MONSTERS_BUG_4: number;
declare const TILE_MONSTERS_MONSTERS_BUG_5: number;
declare const TILE_MONSTERS_MONSTERS_BUG_6: number;
declare const TILE_MONSTERS_MONSTERS_BUG_7: number;
declare const TILE_MONSTERS_MONSTERS_BUG_8: number;
declare const TILE_MONSTERS_MONSTERS_BUG_9: number;
declare const TILE_MONSTERS_MONSTERS_SPIDER_1: number;
declare const TILE_MONSTERS_MONSTERS_SPIDER_2: number;
declare const TILE_MONSTERS_MONSTERS_SPIDER_3: number;
declare const TILE_MONSTERS_MONSTERS_SPIDER_4: number;
declare const TILE_MONSTERS_MONSTERS_SPIDER_5: number;
declare const TILE_MONSTERS_MONSTERS_SPIDER_6: number;
declare const TILE_MONSTERS_MONSTERS_SPIDER_7: number;
declare const TILE_MONSTERS_MONSTERS_ANT_1: number;
declare const TILE_MONSTERS_MONSTERS_ANT_2: number;
declare const TILE_MONSTERS_MONSTERS_ANT_3: number;
declare const TILE_MONSTERS_MONSTERS_ANT_4: number;
declare const TILE_MONSTERS_MONSTERS_ANT_5: number;
declare const TILE_MONSTERS_MONSTERS_ANT_6: number;
declare const TILE_MONSTERS_MONSTERS_ANT_7: number;
declare const TILE_MONSTERS_MONSTERS_ANT_8: number;
declare const TILE_MONSTERS_MONSTERS_MUMMY_1: number;
declare const TILE_MONSTERS_MONSTERS_MUMMY_2: number;
declare const TILE_MONSTERS_MONSTERS_MUMMY_3: number;
declare const TILE_MONSTERS_MONSTERS_MUMMY_4: number;
declare const TILE_MONSTERS_MONSTERS_MUMMY_5: number;
declare const TILE_MONSTERS_MONSTERS_MUMMY_6: number;
declare const TILE_MONSTERS_MONSTERS_MUMMY_7: number;
declare const TILE_MONSTERS_MONSTERS_MUMMY_8: number;
declare const TILE_ITEMS_RINGS_RING_1: number;
declare const TILE_ITEMS_RINGS_RING_2: number;
declare const TILE_ITEMS_RINGS_RING_3: number;
declare const TILE_ITEMS_RINGS_RING_4: number;
declare const TILE_ITEMS_RINGS_RING_5: number;
declare const TILE_ITEMS_RINGS_RING_6: number;
declare const TILE_ITEMS_RINGS_RING_7: number;
declare const TILE_ITEMS_RINGS_RING_8: number;
declare const TILE_ITEMS_RINGS_RING_9: number;
declare const TILE_ITEMS_RINGS_RING_10: number;
declare const TILE_ITEMS_RINGS_RING_11: number;
declare const TILE_ITEMS_RINGS_RING_12: number;
declare const TILE_ITEMS_RINGS_RING_13: number;
declare const TILE_ITEMS_RINGS_RING_14: number;
declare const TILE_ITEMS_RINGS_RING_15: number;
declare const TILE_ITEMS_RINGS_RING_16: number;
declare const TILE_ITEMS_RINGS_RING_17: number;
declare const TILE_ITEMS_RINGS_RING_18: number;
declare const TILE_ITEMS_RINGS_RING_19: number;
declare const TILE_ITEMS_RINGS_RING_20: number;
declare const TILE_ITEMS_RINGS_RING_21: number;
declare const TILE_ITEMS_RINGS_RING_22: number;
declare const TILE_ITEMS_RINGS_RING_23: number;
declare const TILE_ITEMS_RINGS_RING_24: number;
declare const TILE_ITEMS_RINGS_RING_25: number;
declare const TILE_ITEMS_RINGS_RING_26: number;
declare const TILE_ITEMS_RINGS_RING_27: number;
declare const TILE_ITEMS_RINGS_RING_28: number;
declare const TILE_ITEMS_RINGS_RING_29: number;
declare const TILE_ITEMS_RINGS_RING_30: number;
declare const TILE_ITEMS_RINGS_RING_31: number;
declare const TILE_ITEMS_RINGS_RING_32: number;
declare const TILE_ITEMS_RINGS_RING_33: number;
declare const TILE_ITEMS_RINGS_RING_34: number;
declare const TILE_ITEMS_RINGS_RING_35: number;
declare const TILE_ITEMS_RINGS_RING_36: number;
declare const TILE_ITEMS_RINGS_RING_37: number;
declare const TILE_ITEMS_RINGS_RING_38: number;
declare const TILE_ITEMS_RINGS_RING_39: number;
declare const TILE_ITEMS_RINGS_RING_40: number;
declare const TILE_ITEMS_RINGS_RING_41: number;
declare const TILE_ITEMS_RINGS_RING_42: number;
declare const TILE_ITEMS_RINGS_RING_43: number;
declare const TILE_ITEMS_RINGS_RING_44: number;
declare const TILE_ITEMS_RINGS_RING_45: number;
declare const TILE_ITEMS_RINGS_RING_46: number;
declare const TILE_ITEMS_RINGS_RING_47: number;
declare const TILE_ITEMS_RINGS_RING_48: number;
declare const TILE_ITEMS_RINGS_RING_49: number;
declare const TILE_ITEMS_RINGS_RING_MAGIC_1: number;
declare const TILE_ITEMS_RINGS_RING_MAGIC_2: number;
declare const TILE_ITEMS_RINGS_RING_MAGIC_3: number;
declare const TILE_ITEMS_RINGS_RING_MAGIC_4: number;
declare const TILE_ITEMS_RINGS_RING_MAGIC_5: number;
declare const TILE_ITEMS_RINGS_NECKLACE_1: number;
declare const TILE_ITEMS_RINGS_NECKLACE_2: number;
declare const TILE_ITEMS_RINGS_NECKLACE_3: number;
declare const TILE_ITEMS_RINGS_NECKLACE_4: number;
declare const TILE_ITEMS_RINGS_NECKLACE_5: number;
declare const TILE_ITEMS_RINGS_NECKLACE_6: number;
declare const TILE_ITEMS_RINGS_NECKLACE_7: number;
declare const TILE_ITEMS_RINGS_NECKLACE_8: number;
declare const TILE_ITEMS_RINGS_NECKLACE_9: number;
declare const TILE_ITEMS_RINGS_NECKLACE_10: number;
declare const TILE_ITEMS_RINGS_NECKLACE_11: number;
declare const TILE_ITEMS_RINGS_NECKLACE_12: number;
declare const TILE_ITEMS_RINGS_NECKLACE_13: number;
declare const TILE_ITEMS_RINGS_NECKLACE_14: number;
declare const TILE_ITEMS_RINGS_NECKLACE_15: number;
declare const TILE_ITEMS_RINGS_NECKLACE_16: number;
declare const TILE_ITEMS_RINGS_NECKLACE_17: number;
declare const TILE_ITEMS_RINGS_NECKLACE_18: number;
declare const TILE_ITEMS_RINGS_NECKLACE_19: number;
declare const TILE_ITEMS_RINGS_NECKLACE_20: number;
declare const TILE_ITEMS_RINGS_NECKLACE_21: number;
declare const TILE_ITEMS_RINGS_NECKLACE_22: number;
declare const TILE_ITEMS_RINGS_NECKLACE_23: number;
declare const TILE_ITEMS_RINGS_NECKLACE_24: number;
declare const TILE_ITEMS_RINGS_NECKLACE_25: number;
declare const TILE_ITEMS_RINGS_NECKLACE_26: number;
declare const TILE_ITEMS_RINGS_NECKLACE_27: number;
declare const TILE_ITEMS_RINGS_NECKLACE_28: number;
declare const TILE_ITEMS_RINGS_NECKLACE_29: number;
declare const TILE_ITEMS_RINGS_NECKLACE_30: number;
declare const TILE_ITEMS_GEMS_DIAMON_1: number;
declare const TILE_ITEMS_GEMS_DIAMON_2: number;
declare const TILE_ITEMS_GEMS_PEARL_1: number;
declare const TILE_ITEMS_GEMS_PEARL_2: number;
declare const TILE_OBJECTS_CHEST_CHEST_1: number;
declare const TILE_OBJECTS_CHEST_CHEST_2: number;
declare const TILE_OBJECTS_CHEST_CHEST_3: number;
declare const TILE_OBJECTS_CHEST_CHEST_4: number;
declare const TILE_OBJECTS_CHEST_CHEST_5: number;
declare const TILE_OBJECTS_CHEST_CHEST_6: number;
declare const TILE_ITEMS_WEAPONS_SWORD_BROKEN_1: number;
declare const TILE_ITEMS_WEAPONS_SWORD_BROKEN_2: number;
declare const TILE_ITEMS_WEAPONS_SWORD_BROKEN_3: number;
declare const TILE_ITEMS_WEAPONS_SWORD_BROKEN_4: number;
declare const TILE_ITEMS_WEAPONS_SWORD_BROKEN_5: number;
declare const TILE_ITEMS_WEAPONS_SWORD_1: number;
declare const TILE_ITEMS_WEAPONS_SWORD_2: number;
declare const TILE_ITEMS_WEAPONS_SWORD_3: number;
declare const TILE_ITEMS_WEAPONS_SWORD_4: number;
declare const TILE_ITEMS_WEAPONS_SWORD_5: number;
declare const TILE_ITEMS_WEAPONS_SWORD_6: number;
declare const TILE_ITEMS_WEAPONS_SWORD_7: number;
declare const TILE_ITEMS_WEAPONS_SWORD_8: number;
declare const TILE_ITEMS_WEAPONS_SWORD_9: number;
declare const TILE_ITEMS_WEAPONS_SWORD_10: number;
declare const TILE_ITEMS_WEAPONS_SWORD_11: number;
declare const TILE_ITEMS_WEAPONS_SWORD_12: number;
declare const TILE_ITEMS_WEAPONS_SWORD_MAGIC_1: number;
declare const TILE_ITEMS_GEMS_COPPER_1: number;
declare const TILE_ITEMS_GEMS_SILVER_1: number;
declare const TILE_ITEMS_GEMS_GOLD_1: number;
declare const TILE_ITEMS_GEMS_OBSIDIAN: number;
declare const TILE_ITEMS_GEMS_CRYSTAL_1: number;
declare const TILE_ITEMS_FOOD_BEER_1: number;
declare const TILE_ITEMS_FOOD_WINE_1: number;
declare const TILE_ITEMS_FOOD_BREAD_1: number;
declare const TILE_ITEMS_FOOD_BREAD_2: number;
declare const TILE_ITEMS_FOOD_MEAT_1: number;
declare const TILE_ITEMS_FOOD_MEAT_2: number;
declare const TILE_ITEMS_FOOD_POTION_1: number;
declare const TILE_ITEMS_FOOD_POTION_2: number;
declare const TILE_ITEMS_FOOD_POTION_POISON_1: number;
declare const TILE_ITEMS_FOOD_POTION_3: number;
declare const TILE_ITEMS_FOOD_POTION_4: number;
declare const TILE_ITEMS_FOOD_POTION_5: number;
declare const TILE_ITEMS_FOOD_POTION_6: number;
declare const TILE_ITEMS_FOOD_POTION_7: number;
declare const TILE_ITEMS_FOOD_POTION_8: number;
declare const TILE_ITEMS_FOOD_POTION_9: number;
declare const TILE_ITEMS_FOOD_POTION_10: number;
declare const TILE_ITEMS_FOOD_POTION_EMPTY_1: number;
declare const TILE_ITEMS_FOOD_POTION_11: number;
declare const TILE_ITEMS_FOOD_POTION_12: number;
declare const TILE_ITEMS_FOOD_POTION_13: number;
declare const TILE_ITEMS_FOOD_POTION_14: number;
declare const TILE_ITEMS_FOOD_POTION_15: number;
declare const TILE_ITEMS_FOOD_POTION_16: number;
declare const TILE_ITEMS_FOOD_POTION_17: number;
declare const TILE_ITEMS_FOOD_POTION_18: number;
declare const TILE_ITEMS_FOOD_POTION_19: number;
declare const TILE_ITEMS_FOOD_POTION_EMPTY_2: number;
declare const TILE_ITEMS_FOOD_POTION_EMPTY_3: number;
declare const TILE_ITEMS_FOOD_POTION_EMPTY_4: number;
declare const TILE_ITEMS_FOOD_POTION_20: number;
declare const TILE_ITEMS_FOOD_POTION_21: number;
declare const TILE_ITEMS_FOOD_POTION_22: number;
declare const TILE_ITEMS_FOOD_POTION_23: number;
declare const TILE_ITEMS_FOOD_POTION_24: number;
declare const TILE_ITEMS_FOOD_POTION_25: number;
declare const TILE_ITEMS_FOOD_POTION_26: number;
declare const TILE_ITEMS_FOOD_POTION_27: number;
declare const TILE_ITEMS_FOOD_POTION_EMPTY_5: number;
declare const TILE_ITEMS_FOOD_POTION_28: number;
declare const TILE_ITEMS_FOOD_POTION_29: number;
declare const TILE_ITEMS_FOOD_POTION_30: number;
declare const TILE_ITEMS_FOOD_POTION_31: number;
declare const TILE_ITEMS_FOOD_POTION_32: number;
declare const TILE_ITEMS_FOOD_POTION_33: number;
declare const TILE_ITEMS_FOOD_POTION_34: number;
declare const TILE_ITEMS_FOOD_POTION_35: number;
declare const TILE_ITEMS_FOOD_POTION_36: number;
declare const TILE_ITEMS_FOOD_POTION_EMPTY_6: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_1: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_2: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_3: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_4: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_5: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_6: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_7: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_8: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_9: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_10: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_11: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_12: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_13: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_14: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_15: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_16: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_17: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_18: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_19: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_20: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_21: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_22: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_23: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_24: number;
declare const TILE_ITEMS_FOOD_MUSHROOM_25: number;
declare const TILE_OBJECTS_DOORS_DUNGEON_CLOSED_1: number;
declare const TILE_OBJECTS_DOORS_DUNGEON_CLOSED_2: number;
declare const TILE_OBJECTS_DOORS_DUNGEON_CLOSED_3: number;
declare const TILE_OBJECTS_DOORS_DUNGEON_OPEN_1: number;
declare const TILE_OBJECTS_DOORS_DUNGEON_OPEN_2: number;
declare const TILE_OBJECTS_DOORS_DUNGEON_OPEN_3: number;
declare const TILE_OBJECTS_DOORS_DUNGEON_BROKEN_1: number;
declare const TILE_OBJECTS_DOORS_DUNGEON_BROKEN_2: number;
declare const TILE_OBJECTS_DOORS_DUNGEON_BROKEN_3: number;
declare const TILE_OBJECTS_DOORS_SHOP_1: number;
declare const TILE_OBJECTS_DOORS_TAVERN_1: number;
declare const TILE_OBJECTS_DOORS_STAIRS_DUNGEON_UP_1: number;
declare const TILE_OBJECTS_DOORS_STAIRS_DUNGEON_UP_2: number;
declare const TILE_OBJECTS_DOORS_STAIRS_DUNGEON_UP_3: number;
declare const TILE_OBJECTS_DOORS_STAIRS_DUNGEON_DOWN_1: number;
declare const TILE_OBJECTS_DOORS_STAIRS_DUNGEON_DOWN_2: number;
declare const TILE_OBJECTS_DOORS_STAIRS_DUNGEON_DOWN_3: number;
declare const TILE_HUMANS_CORPSE_CORPSE_1: number;
declare const TILE_HUMANS_CORPSE_CORPSE_2: number;
declare const TILE_HUMANS_CORPSE_CORPSE_3: number;
declare const TILE_HUMANS_CORPSE_CORPSE_4: number;
declare const TILE_HUMANS_CORPSE_CORPSE_5: number;
declare const TILE_HUMANS_CORPSE_CORPSE_6: number;
declare const TILE_HUMANS_CORPSE_CORPSE_7: number;
declare const TILE_HUMANS_CORPSE_CORPSE_8: number;
declare const TILE_ANIMALS_ANIMALS_BEE_1: number;
declare const TILE_ANIMALS_ANIMALS_HORSE_1: number;
declare const TILE_ANIMALS_ANIMALS_HORSE_2: number;
declare const TILE_ANIMALS_ANIMALS_DEER_1: number;
declare const TILE_ANIMALS_ANIMALS_CHICKEN_1: number;
declare const TILE_ANIMALS_ANIMALS_COW_1: number;
declare const TILE_ANIMALS_ANIMALS_DONKEY_1: number;
declare const TILE_ANIMALS_ANIMALS_BIRD_1: number;
declare const TILE_ANIMALS_ANIMALS_BIRD_2: number;
declare const TILE_ANIMALS_ANIMALS_BIRD_3: number;
declare const TILE_ANIMALS_ANIMALS_BIRD_4: number;
declare const TILE_ANIMALS_ANIMALS_BIRD_5: number;
declare const TILE_ANIMALS_ANIMALS_BIRD_6: number;
declare const TILE_ANIMALS_ANIMALS_BIRD_7: number;
declare const TILE_ANIMALS_ANIMALS_BIRD_8: number;
declare const TILE_ANIMALS_ANIMALS_BIRD_9: number;
declare const TILE_ANIMALS_ANIMALS_CAT_1: number;
declare const TILE_ANIMALS_ANIMALS_CAT_2: number;
declare const TILE_ANIMALS_ANIMALS_DOG_1: number;
declare const TILE_ANIMALS_ANIMALS_DOG_2: number;
declare const TILE_ANIMALS_ANIMALS_DOG_3: number;
declare const TILE_ANIMALS_ANIMALS_DOG_4: number;
declare const TILE_ANIMALS_ANIMALS_DOG_5: number;
declare const TILE_ANIMALS_ANIMALS_DOG_6: number;
declare const TILE_ANIMALS_ANIMALS_DOG_7: number;
declare const TILE_ANIMALS_ANIMALS_DOG_8: number;
declare const TILE_ANIMALS_ANIMALS_DOG_9: number;
declare const TILE_ANIMALS_ANIMALS_DOG_10: number;
declare const TILE_ANIMALS_ANIMALS_DOG_11: number;
declare const TILE_ANIMALS_ANIMALS_DOG_12: number;
declare const TILE_ANIMALS_ANIMALS_CAT_3: number;
declare const TILE_ANIMALS_ANIMALS_SNAKE_1: number;
declare const TILE_ANIMALS_ANIMALS_SNAKE_2: number;
declare const TILE_ANIMALS_ANIMALS_CAT_4: number;
declare const TILE_ANIMALS_ANIMALS_CAT_5: number;
declare const TILE_ANIMALS_ANIMALS_CAT_6: number;
declare const TILE_ANIMALS_ANIMALS_CAT_7: number;
declare const TILE_ANIMALS_ANIMALS_CAT_8: number;
declare const TILE_ANIMALS_ANIMALS_SQUIRREL_1: number;
declare const TILE_ANIMALS_ANIMALS_TURTLE_1: number;
declare const TILE_ANIMALS_ANIMALS_DEER_2 : number;
declare const TILE_ANIMALS_ANIMALS_MOUSE_1: number;
declare const TILE_ANIMALS_ANIMALS_FROG_1: number;
declare const TILE_ANIMALS_ANIMALS_COCKROACH_1: number;
declare const TILE_ANIMALS_ANIMALS_SHEEP_1: number;
declare const TILE_ANIMALS_ANIMALS_PIG_1: number;
declare const TILE_ANIMALS_ANIMALS_FOX_1: number;
declare const TILE_ANIMALS_ANIMALS_BEE_2: number;
declare const TILE_ANIMALS_ANIMALS_PORCUPINE_1: number;
declare const TILE_ITEMS_FOOD_TOMATO_1: number;
declare const GAMEOBJECT_PROP_MUSHROOM: number;
declare const GAMEOBJECT_INTERNAL_WORLD_SPAWNER: number;
declare const MAP_TYPE_WORLD: number;
declare const MAP_TYPE_DUNGEON: number;
declare const MAP_TYPE_CITY: number;
declare const MAP_TYPE_TOWN: number;
declare const MAP_TYPE_VILLAGE: number;
declare const MAP_TYPE_CAMP: number;
declare const MAP_TYPE_RUINS: number;
declare const MAP_TYPE_CAVE: number;
declare const MAP_TYPE_FOREST: number;
declare const MAP_GENERATOR_TYPE_RECTANGLE_MAP: number;
declare const MAP_GENERATOR_TYPE_CELLULAR_AUTOMATA: number;
declare const MAP_GENERATOR_TYPE_DUNGEON: number;
declare const MAP_GENERATOR_TYPE_BASIC_RANDOM_ROOMS: number;
declare const MESSAGE_TYPE_WHISPER: number;
declare const MESSAGE_TYPE_NORMAL: number;
declare const MESSAGE_TYPE_YELL: number;
declare const EQUIP_LOCATION_NONE: number;
declare const EQUIP_LOCATION_HEAD: number;
declare const EQUIP_LOCATION_NECK: number;
declare const EQUIP_LOCATION_SHOULDERS: number;
declare const EQUIP_LOCATION_CHEST: number;
declare const EQUIP_LOCATION_BACK: number;
declare const EQUIP_LOCATION_WRISTS: number;
declare const EQUIP_LOCATION_HANDS: number;
declare const EQUIP_LOCATION_WAIST: number;
declare const EQUIP_LOCATION_LEGS: number;
declare const EQUIP_LOCATION_FEET: number;
declare const EQUIP_LOCATION_RING: number;
declare const EQUIP_LOCATION_TRINKET: number;
declare const EQUIP_LOCATION_MAINHAND: number;
declare const EQUIP_LOCATION_OFFHAND: number;
declare const EQUIP_LOCATION_RANGED: number;
declare const EQUIP_LOCATION_AMMO: number;
declare const ITEM_RARITY_COMMON: number;
declare const ITEM_RARITY_UNCOMMON: number;
declare const ITEM_RARITY_RARE: number;
declare const ITEM_RARITY_EPIC: number;
declare const ITEM_RARITY_LEGENDARY: number;
declare const MOVE_DIRECTION_NORTH: number;
declare const MOVE_DIRECTION_SOUTH: number;
declare const MOVE_DIRECTION_EAST: number;
declare const MOVE_DIRECTION_WEST: number;
declare const MOVE_DIRECTION_NORTH_EAST: number;
declare const MOVE_DIRECTION_NORTH_WEST: number;
declare const MOVE_DIRECTION_SOUTH_EAST: number;
declare const MOVE_DIRECTION_SOUTH_WEST: number;
declare const NPC_TYPE_HUMAN: number;
declare const NPC_TYPE_ANIMAL: number;
declare const NPC_SUBTYPE_MUSHROOM_FINDER: number;
declare const NPC_SUBTYPE_CAT: number;
declare const NPC_SUBTYPE_DOG: number;
declare const GAMEOBJECT_INTERNAL_SPAWNER_GOLD: number;
declare const GAMEOBJECT_INTERNAL_SPAWNER_SILVER: number;
declare const GAMEOBJECT_PROP_CHEST: number;


// Declare functions
/**
 * 
 *
 * @param npcType string
 * @param npcSubType string
 * @param context any
 * @returns void
 */

declare function add_ai_brain_by_type(
  npcType: string,
  npcSubType: string,
  context: any,
): void;


/**
 * 
 *
 * @param name string
 * @param context any
 * @returns void
 */

declare function add_ai_brain_by_name(
  name: string,
  context: any,
): void;


/**
 * 
 *
 * @param mapType number
 * @param callBack any
 * @returns void
 */

declare function add_map_generator(
  mapType: number,
  callBack: any,
): void;


/**
 * 
 *
 * @param callBack any
 * @returns void
 */

declare function add_city_map_generator(
  callBack: any,
): void;


/**
 * 
 *
 * @param callBack any
 * @returns void
 */

declare function add_dungeon_map_generator(
  callBack: any,
): void;


/**
 * 
 *
 * @param mapType number
 * @param callBack any
 * @returns void
 */

declare function add_map_strategy(
  mapType: number,
  callBack: any,
): void;


/**
 * Adds an event to the engine ready event.
 *
 * @param callBack any
 * @returns void
 */

declare function on_engine_ready_event(
  callBack: any,
): void;


/**
 * Adds a game object action to the game object.
 *
 * @param gameObjectType string
 * @param callBack any
 * @returns void
 */

declare function add_game_object_action(
  gameObjectType: string,
  callBack: any,
): void;


/**
 * Adds a scheduled game object action to the game object.
 *
 * @param gameObjectType string
 * @param interval number
 * @param callBack any
 * @returns void
 */

declare function add_scheduled_game_object_action(
  gameObjectType: string,
  interval: number,
  callBack: any,
): void;


/**
 * 
 *
 * @param gold number
 * @returns void
 */

declare function set_player_initial_gold(
  gold: number,
): void;


/**
 * 
 *
 * @param itemName string
 * @param quantity number
 * @returns void
 */

declare function set_player_initial_item(
  itemName: string,
  quantity: number,
): void;


/**
 * 
 *
 * @param min number
 * @param max number
 * @returns number
 */

declare function random_range(
  min: number,
  max: number,
): number;


/**
 * 
 *
 * @returns boolean
 */

declare function random_bool(
): boolean;


/**
 * 
 *
 * @param expression string
 * @returns number
 */

declare function parse_dice_exp(
  expression: string,
): number;


/**
 * Get a random item from a list
 *
 * @param list any
 * @returns any
 */

declare function random_list(
  list: any,
): any;


/**
 * 
 *
 * @param text string
 * @param args any
 * @returns void
 */

declare function log(
  text: string,
  args?: any,
): void;


/**
 * 
 *
 * @param serverMotd string
 * @returns void
 */

declare function set_server_motd(
  serverMotd: string,
): void;


/**
 * 
 *
 * @param serverName string
 * @returns void
 */

declare function set_server_name(
  serverName: string,
): void;


/**
 * 
 *
 * @param type any
 * @returns void
 */

declare function add_game_object_type(...params: string[]): void;


/**
 * 
 *
 * @param type string
 * @param subType string
 * @returns any
 */

declare function add_npc_type(
  type: string,
  subType: string,
): any;


/**
 * 
 *
 * @param id number
 * @param name string
 * @param category string
 * @param subcategory string
 * @param tag string
 * @param isTransparent boolean
 * @returns any
 */

declare function add_tile(
  id: number,
  name: string,
  category: string,
  subcategory: string,
  tag: string,
  isTransparent: boolean,
): any;


/**
 * 
 *
 * @param name string
 * @param description string
 * @param tileName string
 * @param gameObjectType string
 * @param data string
 * @returns void
 */

declare function add_game_object(
  name: string,
  description: string,
  tileName: string,
  gameObjectType: string,
  data: string,
): void;


/**
 * 
 *
 * @param names any
 * @returns void
 */

declare function add_item_type(
  names: any,
): void;


/**
 * 
 *
 * @param names any
 * @returns void
 */

declare function add_item_category_type(
  names: any,
): void;


/**
 * 
 *
 * @param id string
 * @param content string
 * @returns void
 */

declare function add_text_content(
  id: string,
  content: string,
): void;


/**
 * 
 *
 * @param gameObjectName string
 * @param textContentId string
 * @returns void
 */

declare function attach_text_content_to_item(
  gameObjectName: string,
  textContentId: string,
): void;


/**
 * 
 *
 * @param name string
 * @param description string
 * @param weight number
 * @param tileName string
 * @param category string
 * @param type string
 * @param equipLocation number
 * @param itemRarity number
 * @param sellDice string
 * @param buyDice string
 * @param attackDice string
 * @param defenseDice string
 * @param speed string
 * @returns void
 */

declare function add_item(
  name: string,
  description: string,
  weight: number,
  tileName: string,
  category: string,
  type: string,
  equipLocation: number,
  itemRarity: number,
  sellDice: string,
  buyDice: string,
  attackDice: string,
  defenseDice: string,
  speed: string,
): void;

