database:
  connection_string: Data Source={DATABASE_DIRECTORY}DarkStar.db;Version=3;
  database_type: SqlLite
  recreate_database: true
network_server:
  address: 0.0.0.0
  port: 9000
logger:
  enable_debug: true
assemblies:
  assembly_names: []
maps:
  save_every_minutes: 1
  worlds:
    num: 1
    width: 1000
    height: 1000
  cities:
    num: 3
  dungeons:
    num: 15
experimental:
  compiler:
    enable_c_sharp_compiler: false